server:
  port: 8083

spring:
  application:
    name: agendador-tarefas
  data:
    mongodb:
      uri: mongodb://localhost:27017/agendador-tarefas
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json

microservices:
  notificacao-email:
    url: http://localhost:8084


cron:
  horario: 0 * * * * *
  timezone: America/Sao_Paulo