server:
  port: 8082
spring:
  application:
    name: cadastro-usuarios
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cadastro-usuarios}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8082/.well-known/jwks.json}

jwt:
  public:
    key: ${JWT_PUBLIC_KEY_PATH:classpath:keys/public.pem}
  private:
    key: ${JWT_PRIVATE_KEY_PATH:classpath:keys/private.pem}